### ISSUE TITLE
codacy: Perhaps 'bundle' could be replaced by a local variable.

### ISSUE THREAD

**Issue by JoachimSchwarte** [JoachimSchwarte/MultiVaLCA#25]
Ursache: Die genannte Variable wird nur in einer einzigen Methode benötigt und daher reicht die Deklaration als lokale Variable dort.

Betrifft die Dateien:

src/de/unistuttgart/iwb/multivalcagui/CFListPanel.java
src/de/unistuttgart/iwb/multivalcagui/ComponentListPanel.java
src/de/unistuttgart/iwb/multivalcagui/CompositionListPanel.java
src/de/unistuttgart/iwb/multivalcagui/CompositionPanel.java
src/de/unistuttgart/iwb/multivalcagui/DeklarationListPanel.java
src/de/unistuttgart/iwb/multivalcagui/EvalMListPanel.java
src/de/unistuttgart/iwb/multivalcagui/ImpactListPanel.java
src/de/unistuttgart/iwb/multivalcagui/XMLExportAction.java
src/de/unistuttgart/iwb/multivalcagui/XMLImportAction.java
src/de/unistuttgart/iwb/multivalcagui/FlowListPanel.java
src/de/unistuttgart/iwb/multivalcagui/InfoPanel.java
src/de/unistuttgart/iwb/multivalcagui/LciCalcPanel.java
src/de/unistuttgart/iwb/multivalcagui/ProcModListPanel.java
src/de/unistuttgart/iwb/multivalcagui/ProductSystemListPanel.java

**Comment by HeLuHein** [comment]
#25 erledigt.
